---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: bash

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
inputs:
  - name: sample-pipelines
  - name: om-cli
  - name: secrets

run:
  path: sample-pipelines/tasks/configure-pas/task.sh
